; ===== XIAO ESP32-C3 + Arduino + USB-CDC serial =====
[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_speed = 512000 

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  https://github.com/adafruit/Adafruit_VL6180X.git
